name: UU_runner
description: A simple 2D game using Flame.

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.0.0
  flutter_bloc: ^9.1.0 # Optional, for state management
  # Add any other necessary dependencies here

dev_dependencies:
  flutter_test:
    sdk: flutter
